version: '3.8'

services:
  php-fpm:
    build:
      context: ./docker
    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php-fpm